spring.application.name=location-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/ridehailing
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always